In [2]:
import numpy as np

##create array using numpy
##create an 1d array

arr1=np.array([1,3,5,6,8])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 3 5 6 8]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2=np.array([3,7,5,3,0])
arr2.reshape(1,5)


array([[3, 7, 5, 3, 0]])

In [ ]:
##2d-array
arr2=np.array([[2,7,8,4,6],[5,8,2,7,1]])
print(arr2)
print(arr2.shape)####shape is use to show shape or dimension of the array



[[2 7 8 4 6]
 [5 8 2 7 1]]
(2, 5)


array([0, 2, 4, 6, 8])

In [4]:
##arange is use to made a array 
##reshape is use to give dimension of the array.
###arange(start value,end value,step-value)
# ##reshape(no. of rows,no. of columns)


np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [12]:
np.ones((3,4))


###ones is use to make array only consist number 1
##ones(row,column)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#### identity matrix 
####eye(no. of rows) is use to make identity matrix 


np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
###some attributes of numpy
arr=np.array([[2,4,6],[5,8,1]])

print("array:\n",arr)
print("shape :",arr.shape)
print("number of dimension :",arr.ndim)
print("size (number of element) :",arr.size)
print("Data type :",arr.dtype)
print("Item size(in bytes):",arr.itemsize)

array:
 [[2 4 6]
 [5 8 1]]
shape : (2, 3)
number of dimension : 2
size (number of element) : 6
Data type : int64
Item size(in bytes): 8


In [18]:
###numpy vectorized operation

arr1=np.array([56,84,32,23])
arr2=np.array([23,78,90,67])

### ELEMENT  WISE ADDITION

print("Addition :",arr1+arr2)
### ELEMENT  WISE SUBTRACTION

print("subtraction :",arr1-arr2)

### ELEMENT  WISE MULTIPLICATION

print("multiplication :",arr1*arr2)

### ELEMENT  WISE DIVISION

print("division :",arr1/arr2)

Addition : [ 79 162 122  90]
subtraction : [ 33   6 -58 -44]
multiplication : [1288 6552 2880 1541]
division : [2.43478261 1.07692308 0.35555556 0.34328358]


In [ ]:
### universal Function ## mathematical function
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
####array licing and indexing

arr=np.array([[1,8,9,6],[5,6,7,9],[4,8,9,0]])
print(arr)

arr[0][0]
arr[1:,2:]
arr[0:2,2:]

[[1 8 9 6]
 [5 6 7 9]
 [4 8 9 0]]


array([[9, 6],
       [7, 9]])

In [25]:
####modify array element

arr[0,0]=100
print(arr)

[[100   8   9   6]
 [  5   6   7   9]
 [  4   8   9   0]]


In [26]:
arr[1:]=100
print(arr)

[[100   8   9   6]
 [100 100 100 100]
 [100 100 100 100]]


In [27]:
#### statistical concepts --- normalisation
#to have a mean of 0 and standard deviation of 1
data= np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean =np.mean(data)
st_dev= np.std(data)

#normalise the data

normalized_data= (data-mean)/st_dev
print("normalised data:",normalized_data)



normalised data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [28]:
data=np.array([1,2,3,4,5,6,7,8,9])

mean=np.mean(data)
print("mean :",mean)

#meadian
median=np.median(data)
print("median",median)

#standard deviation
st_dev=np.std(data)
print("standard deviation :",st_dev)

#variance
variance=np.var(data)
print("variance",variance)


mean : 5.0
median 5.0
standard deviation : 2.581988897471611
variance 6.666666666666667


In [33]:
###logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5
data[(data>5) & (data<8)]

array([6, 7])